language: node_js
node_js:
  - 'node'

before_install:
  # - rvm install 2.2.2

install:
  - npm install --global https://github.com/chinesedfan/awesome-lint.git#test_ci
  # - gem install awesome_bot

script:
  - awesome-lint README.md
  # - awesome_bot README.md --allow-redirect --allow-dupe

notifications:
  email:
    on_failure: always
